# Site settings
title: mGBA
email: vi@endrift.com
description: "mGBA is an open-source Game Boy Advance emulator, copyright &copy; 2013&ndash;2018 Vicki Pfau. This project is not affiliated in any way with Nintendo. Game Boy Advance is a registered trademark of Nintendo Co., Ltd."
baseurl: ""
url: "https://mgba.io"
twitter_username: mgba_emu
github_username:  mgba-emu
exclude: ['Gemfile.lock', 'Gemfile']

paginate: 10
paginate_path: "/page/:num/"

plugins:
 - jekyll-paginate
 - jekyll-toc
 - jekyll-youtube
 - jekyll-redirect-from

# Build settings
markdown: kramdown
permalink: pretty
excerpt_separator: "<!--more-->"
toc:
  min_level: 2
